name: build and deploy
on:
  workflow_dispatch:

jobs:
  rag_process:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build image
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USER }}/ecs-rag:${{ github.sha }} .

      - name: scan image
        uses: aquasecurity/trivy-action@0.25.0
        with:
          format: 'table'
          image-ref: ${{ secrets.DOCKER_USER }}/ecs-rag:${{ github.sha }}
          severity: 'HIGH,CRITICAL'

      - name: push image
        run: docker push ${{ secrets.DOCKER_USER }}/ecs-rag:${{ github.sha }}
